---
- name: aliases
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/aliases/alias[name/text()="{{ item.0.name }}"]/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_alias | default([]) }}"
    - settings
...
