---
- name: Count dnsservers set
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/system/dnsserver
    count: yes
  register: dnsservercount

- name: Dnsservers
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/system
    add_children: 
      - dnsserver: "{{ item }}"
    pretty_print: yes
  when: dnsservercount.count == 0
  with_items: 
    "{{ dnsserver }}"

- set_fact:
    dnsallowoverride_state: "present"
  when: dnsallowoverride | default(True)
- set_fact:
    dnsallowoverride_state: "absent"
  when: not (dnsallowoverride | default(True))

- name: Set dnsallowoverride {{ dnsallowoverride_state }}
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/system/dnsallowoverride
    state: "{{ dnsallowoverride_state }}"
    pretty_print: yes

- name: Use the local DNS service as a nameserver for this system
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/system/dnslocalhost
    value: "1"
    pretty_print: yes
  when: dnslocalhost | default(True)

- name: Do not use the local DNS service as a nameserver for this system
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/system/dnslocalhost
    state: absent
    pretty_print: yes
  when: not (dnslocalhost | default(True))
...
