---
- name: interface settings specific for an interface
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/interfaces/{{ item.0.interface }}/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_interfaces_specific }}"
    - settings

- name: interface settings that apply to all interfaces
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: "/opnsense/interfaces/{{ item.1 }}/{{ item.0.element }}"
    value: "{{ item.0.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_interfaces_all }}"
    - interfaces
...
