---
- name: vlan_interfaces - set vlan parent interface
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/interfaces/{{ item.0.interface }}/if
    value: "{{ opn_vlan_parent_interface }}_vlan{{ item.0.vlan }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_vlan_interfaces_common }}"
    - settings
    
- name: vlan_interfaces - set vlan specific interface settings
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/interfaces/{{ item.0.interface }}/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_vlan_interfaces_specific | default([]) + opn_vlan_interfaces_common | default([]) }}"
    - settings
...
